# Datasource configuration in dev environment
server:
  port: 8080
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${HOST}:${PORT}/${DBNAME}
    driver-class-name: org.postgresql.Driver
    username: ${USER}
    password: ${PASS}
    hikari:
      idle-timeout: 10000
      pool-name: ApiPool
      maximum-pool-size: 5

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

ms-files:
  url: http://localhost:8081/ms-files-api

logging:
  level:
    root: info
    org.springframework: info
